name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            artifact: sip
            make_target: sip
          - os: windows-latest
            name: windows
            artifact: sip.exe
            make_target: sip.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl git
    
    - name: Setup MinGW (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-ntldd
          make
          awk
          grep
          coreutils

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      run: |
        export OS=Windows_NT
        # Ensure git is available for version check
        export PATH="/mingw64/bin:/usr/bin:$PATH"
        make sip.exe
        echo "Testing sip.exe:"
        ./sip.exe --version || echo "Version check failed with exit code $?"
        echo "Windows build complete - executable ready for upload"

    - name: Build (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        make ${{ matrix.make_target }}
        strip sip
        ./sip --version
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sip-${{ matrix.name }}
        path: ${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: List downloaded files
      run: |
        echo "=== Downloaded files ==="
        find . -type f -name "*" | head -20
        echo "=== Directory structure ==="
        ls -la
        echo "=== sip-linux contents ==="
        ls -la sip-linux/ 2>/dev/null || echo "sip-linux not found"
        echo "=== sip-windows contents ==="
        ls -la sip-windows/ 2>/dev/null || echo "sip-windows not found"
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          sip-linux/sip
          sip-windows/sip.exe
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation
          
          ### Linux
          ```bash
          wget https://github.com/allocata/sip/releases/download/${{ github.ref_name }}/sip
          chmod +x sip
          sudo mv sip /usr/local/bin/
          ```
          
          ### Windows
          ```bash
          # Download sip.exe from the Windows release assets
          # The executable is self-contained and doesn't require additional DLLs
          wget https://github.com/allocata/sip/releases/download/${{ github.ref_name }}/sip.exe
          # Run directly - no external dependencies needed
          ./sip.exe --version
          ```
          
          ### From Source
          ```bash
          git clone https://github.com/allocata/sip.git
          cd sip
          make
          ```
          
          ## What's Changed
          See the commits below for detailed changes.